from enum import Enum, unique


@unique
class MediaPipeBlendShapeEnum(Enum):
    BrowDownLeft = "browDownLeft"
    BrowDownRight = "browDownRight"
    BrowInnerUp = "browInnerUp"
    BrowOuterUpLeft = "browOuterUpLeft"
    BrowOuterUpRight = "browOuterUpRight"
    CheekPuff = "cheekPuff"
    CheekSquintLeft = "cheekSquintLeft"
    CheekSquintRight = "cheekSquintRight"
    EyeBlinkLeft = "eyeBlinkLeft"
    EyeBlinkRight = "eyeBlinkRight"
    EyeLookDownLeft = "eyeLookDownLeft"
    EyeLookDownRight = "eyeLookDownRight"
    EyeLookInLeft = "eyeLookInLeft"
    EyeLookInRight = "eyeLookInRight"
    EyeLookOutLeft = "eyeLookOutLeft"
    EyeLookOutRight = "eyeLookOutRight"
    EyeLookUpLeft = "eyeLookUpLeft"
    EyeLookUpRight = "eyeLookUpRight"
    EyeSquintLeft = "eyeSquintLeft"
    EyeSquintRight = "eyeSquintRight"
    EyeWideLeft = "eyeWideLeft"
    EyeWideRight = "eyeWideRight"
    JawForward = "jawForward"
    JawLeft = "jawLeft"
    JawOpen = "jawOpen"
    JawRight = "jawRight"
    MouthClose = "mouthClose"
    MouthDimpleLeft = "mouthDimpleLeft"
    MouthDimpleRight = "mouthDimpleRight"
    MouthFrownLeft = "mouthFrownLeft"
    MouthFrownRight = "mouthFrownRight"
    MouthFunnel = "mouthFunnel"
    MouthLeft = "mouthLeft"
    MouthLowerDownLeft = "mouthLowerDownLeft"
    MouthLowerDownRight = "mouthLowerDownRight"
    MouthPressLeft = "mouthPressLeft"
    MouthPressRight = "mouthPressRight"
    MouthPucker = "mouthPucker"
    MouthRight = "mouthRight"
    MouthRollLower = "mouthRollLower"
    MouthRollUpper = "mouthRollUpper"
    MouthShrugLower = "mouthShrugLower"
    MouthShrugUpper = "mouthShrugUpper"
    MouthSmileLeft = "mouthSmileLeft"
    MouthSmileRight = "mouthSmileRight"
    MouthStretchLeft = "mouthStretchLeft"
    MouthStretchRight = "mouthStretchRight"
    MouthUpperUpLeft = "mouthUpperUpLeft"
    MouthUpperUpRight = "mouthUpperUpRight"
    NoseSneerLeft = "noseSneerLeft"
    NoseSneerRight = "noseSneerRight"

    HeadRotation = "headRotation"  # not a float type, it's a Rotation class

    # Synthetic blend shapes
    HeadX = "HeadX"
    HeadY = "HeadY"
    HeadZ = "HeadZ"
