from enum import unique, Enum


@unique
class MediaPipeBlendShapeEnum(Enum):
    BrowDownLeft = "browDownLeft"
    BrowDownRight = "browDownRight"
    BrowInnerUp = "browInnerUp"
    BrowOuterUpLeft = "browOuterUpLeft"
    BrowOuterUpRight = "browOuterUpRight"
    CheekPuff = "cheekPuff"
    CheekSquintLeft = "cheekSquintLeft"
    CheekSquintRight = "cheekSquintRight"
    EyeBlinkLeft = "eyeBlinkLeft"
    EyeBlinkRight = "eyeBlinkRight"
    EyeSquintLeft = "eyeSquintLeft"
    EyeSquintRight = "eyeSquintRight"
    EyeWideLeft = "eyeWideLeft"
    EyeWideRight = "eyeWideRight"
    JawForward = "jawForward"
    JawLeft = "jawLeft"
    JawOpen = "jawOpen"
    JawRight = "jawRight"
    MouthClose = "mouthClose"
    MouthDimpleLeft = "mouthDimpleLeft"
    MouthDimpleRight = "mouthDimpleRight"
    MouthFrownLeft = "mouthFrownLeft"
    MouthFrownRight = "mouthFrownRight"
    MouthFunnel = "mouthFunnel"
    MouthLeft = "mouthLeft"
    MouthLowerDownLeft = "mouthLowerDownLeft"
    MouthLowerDownRight = "mouthLowerDownRight"
    MouthPressLeft = "mouthPressLeft"
    MouthPressRight = "mouthPressRight"
    MouthPucker = "mouthPucker"
    MouthRight = "mouthRight"
    MouthRollLower = "mouthRollLower"
    MouthRollUpper = "mouthRollUpper"
    MouthShrugLower = "mouthShrugLower"
    MouthShrugUpper = "mouthShrugUpper"
    MouthSmileLeft = "mouthSmileLeft"
    MouthSmileRight = "mouthSmileRight"
    MouthStretchLeft = "mouthStretchLeft"
    MouthStretchRight = "mouthStretchRight"
    MouthUpperUpLeft = "mouthUpperUpLeft"
    MouthUpperUpRight = "mouthUpperUpRight"
    NoseSneerLeft = "noseSneerLeft"
    NoseSneerRight = "noseSneerRight"

    # Synthetic blend shapes
    EyeXLeft = "EyeXLeft"
    EyeXRight = "EyeXRight"

    EyeYLeft = "EyeYLeft"
    EyeYRight = "EyeYRight"

    HeadX = "HeadX"
    HeadY = "HeadY"
    HeadZ = "HeadZ"

    HeadPitch = "HeadPitch"
    HeadYaw = "HeadYaw"
    HeadRoll = "HeadRoll"
