[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "foxyface"
version = "1.0.6.0"
description = "Real-time face tracking application for VRChat using MediaPipe and Project Babble"
readme = "README.md"
authors = [
    { name = "Jeka8833", email = "foxyface@jeka8833.pp.ua" },
]
maintainers = [
    { name = "Jeka8833", email = "foxyface@jeka8833.pp.ua" },
]
license = "Apache-2.0"
requires-python = ">=3.12"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Win32 (MS Windows)",
    "Environment :: X11 Applications :: Qt",
    "Intended Audience :: End Users/Desktop",
    "Operating System :: OS Independent",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Multimedia :: Graphics :: Capture",
    "Topic :: Scientific/Engineering :: Image Recognition",
    "Topic :: Games/Entertainment",
]
keywords = [
    "foxyface",
    "vrchat",
    "vrcft",
    "face-tracking",
    "mediapipe",
    "facial-tracking",
    "vtuber",
]
dependencies = [
    "mediapipe",
    "PySide6",
    "opencv-contrib-python", # Qt conflict, but I can't do anything
    "dataclass-wizard",
    "OneEuroFilter",
    "packaging",
    "scipy",
    "numpy",
    "soundfile",
    "sounddevice",
    "requests",
    "cv2-enumerate-cameras",
]

[project.optional-dependencies]
default = [
    "onnxruntime-directml; platform_system == 'Windows'",
    "onnxruntime-coreml; platform_system == 'Darwin'",
    "onnxruntime; platform_system == 'Linux'",
]
nvidia = [
    "onnxruntime-gpu",
    "torch",
    "torchvision",
]
rocm = [
    "onnxruntime-rocm",
]
cpu = [
    "onnxruntime",
]
build = [
    "build",
    "twine"
]

[project.scripts]
foxyface = "foxyface.Setup:main"

[project.urls]
Homepage = "https://foxyface.jeka8833.pp.ua"
Documentation = "https://foxyface.jeka8833.pp.ua/docs/FirstSetup/"
Repository = "https://github.com/Jeka8833/FoxyFace"
Issues = "https://github.com/Jeka8833/FoxyFace/issues"
Changelog = "https://github.com/Jeka8833/FoxyFace/releases"

[tool.hatch.build]
exclude = [
    "src/foxyface/ui/qtcreator/.qtcreator",
]

[tool.hatch.build.targets.sdist]
include = [
    "src/foxyface/*.py",
    "src/foxyface/**/*.py",
    "src/foxyface/assets/**/*",
    "Baballonia/src/Baballonia/faceModel.onnx",
]

[tool.hatch.build.targets.wheel]
include = [
    "src/foxyface/*.py",
    "src/foxyface/**/*.py",
    "src/foxyface/assets/**/*",
]
sources = ["src"]

[tool.hatch.build.targets.wheel.force-include]
"Baballonia/src/Baballonia/faceModel.onnx" = "foxyface/assets/baballonia/faceModel.onnx"